### ISSUE TITLE
Size or crop images so they do not squish.

### ISSUE THREAD

**Issue by andrew-sipes** [krupapatell/project-two#3]
![krupapatell github io_project-two_our-work_index html(Main Slide)](https://user-images.githubusercontent.com/25012869/99159946-d800de80-26af-11eb-9c06-49eb5d519efe.png)

https://github.com/krupapatell/project-two/blob/3e085106ef1c07c61fd119e2531b2ecabd0ce843/our-work/index.html#L43

https://github.com/krupapatell/project-two/blob/3e085106ef1c07c61fd119e2531b2ecabd0ce843/css/style.css#L74-L76

Setting the height explicitly here makes the image squish a bit. One way to fix this is to make the height automatic, based on the image's aspect ratio. But if you want the image to stretch the width of the page but still have a max-height, try using [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit).

```css
/* Don't put this in a media query, it needs to apply in both desktop and mobile */
img.ourwork {
    object-fit: cover;
}
```

This should crop the image a tad but not squish it.

![krupapatell github io_project-two_our-work_index html(Main Slide) (1)](https://user-images.githubusercontent.com/25012869/99159941-d0413a00-26af-11eb-8cfe-d726ab50dbcd.png)
